version: "3.7"
services:
    peformancetest:
        image: matthewmxello/redisexpirement:latest
        depends_on:
            - "redis_image"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        links:
            - "redis_image"

    redis_image:
        image: redis
        container_name: cache
        ports:
            - "6379:6379"
